"""NULLIUS public board: static HTML generator for the truth ledger.

Renders the leaderboard (or ledger entries) as a self-contained, color-coded
HTML page -- green for SURVIVES, red for FALSIFIED, amber for UNTESTED -- with
the mechanism, protection factor, ratio, baseline citation, and ledger hash
shown for each claim. This is the public face of the falsifier: the page any
lab, journal, or skeptic can open and audit.

No external dependencies; the HTML is fully self-contained so it can be hosted
on GitHub Pages, a static bucket, or IPFS.
"""


def _color(verdict: str) -> str:
    return {
        "SURVIVES": "#1b7a3d",
        "FALSIFIED": "#b3261e",
        "UNTESTED": "#b26a00",
    }.get(verdict, "#555")


def _esc(s) -> str:
    return (str(s).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))


def generate_html(rows: list, title: str = "NULLIUS Coherence Truth Board",
                  baseline_note: str = "Firmenich et al. 2026 HEOM, "
                  "gamma=7.69e13 Hz, tau_coh=13 fs @310K") -> str:
    """rows: list of verdict-row dicts (as from report_to_row / leaderboard)."""
    counts = {"SURVIVES": 0, "FALSIFIED": 0, "UNTESTED": 0}
    body_rows = []
    for e in rows:
        v = e.get("verdict", "UNTESTED")
        counts[v] = counts.get(v, 0) + 1
        col = _color(v)
        mech = _esc(e.get("mechanism", "none declared"))
        claim = _esc(e.get("claim", "?"))
        src = _esc(e.get("claim_source", ""))
        body_rows.append(f"""
    <tr>
      <td><span class="badge" style="background:{col}">{_esc(v)}</span></td>
      <td><b>{claim}</b><br><span class="sub">{src}</span></td>
      <td>{e.get('kind','')}</td>
      <td>{e.get('claimed_tau_fs',0):.1f} fs</td>
      <td>x{e.get('protection_factor',1):.3g}</td>
      <td>{e.get('allowed_tau_fs',0):.1f} fs</td>
      <td>{e.get('ratio_claimed_over_allowed',0):.2g}</td>
      <td>{mech}</td>
    </tr>""")

    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{_esc(title)}</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin: 2rem;
         background:#0f1115; color:#e6e6e6; }}
  h1 {{ font-size: 1.5rem; }}
  .meta {{ color:#9aa; font-size: .9rem; margin-bottom: 1rem; }}
  .counts span {{ margin-right: 1rem; font-weight: 600; }}
  table {{ border-collapse: collapse; width: 100%; font-size: .9rem; }}
  th, td {{ text-align: left; padding: .5rem .6rem; border-bottom: 1px solid #2a2f3a;
           vertical-align: top; }}
  th {{ color:#9aa; font-weight: 600; }}
  .badge {{ color:#fff; padding:.15rem .5rem; border-radius: 4px; font-size:.8rem; }}
  .sub {{ color:#9aa; font-size:.8rem; }}
  .warn {{ background:#2a1f12; border:1px solid #7a5a1a; color:#f0c674;
           padding:.8rem 1rem; border-radius:6px; margin:1rem 0; font-size:.9rem; }}
  footer {{ margin-top: 2rem; color:#778; font-size:.8rem; }}
</style>
</head>
<body>
  <h1>{_esc(title)}</h1>
  <div class="meta">Baseline: {_esc(baseline_note)} &middot; Generated by kryptorious-qbio-coherence (NULLIUS)</div>
  <div class="warn">
    <b>READ THIS FIRST.</b> The dephasing floor used here
    (Firmenich et al. 2026, &gamma;=7.69&times;10<sup>13</sup> Hz, &tau;<sub>coh</sub>=13 fs @310K)
    is a <b>PREPRINT</b> (publisher: openRxiv; type: posted-content; dated 2026-05-13)
    &mdash; <b>not a peer-reviewed journal article</b>. It is reproducible and widely
    cited, but if a replication moves the floor, every stored verdict must be
    re-verified. Treat verdicts as screening judgments, not settled fact.
  </div>
  <div class="counts">
    <span style="color:#3fbf6f">SURVIVES: {counts['SURVIVES']}</span>
    <span style="color:#ff6b60">FALSIFIED: {counts['FALSIFIED']}</span>
    <span style="color:#ffc04d">UNTESTED: {counts['UNTESTED']}</span>
  </div>
  <table>
    <thead>
      <tr><th>Verdict</th><th>Claim</th><th>Kind</th><th>Claimed</th>
          <th>Prot</th><th>Allowed</th><th>Ratio</th><th>Mechanism</th></tr>
    </thead>
    <tbody>{''.join(body_rows)}
    </tbody>
  </table>
  <footer>
    <p><b>Methodology.</b> Each claim is tested against the dephasing floor
    above. A claim SURVIVES only if its declared protection mechanism yields an
    allowed coherence time at or above the claimed value, within the documented
    protection-factor bounds (collective &radic;N, non-Markovian &le;5&times;,
    entropy &le;50&times;, structured bath &le;20&times;). A claim with no declared
    mechanism that exceeds the bare floor is UNTESTED, not proven. The full
    ruleset and attack-swarm sensitivity analysis ship in the package.</p>
    <p>Every verdict is anchored to the Firmenich 2026 HEOM dephasing floor.
    "SURVIVES" means physics-consistent under the declared mechanism &mdash; it is
    not experimental proof. Audit the ledger:
    <code>python -m qbio_coherence.ledger_cli verify</code>. The ledger is
    hash-chained and tamper-evident; altering any past verdict breaks verification.</p>
  </footer>
</body>
</html>"""
    return html


def write_board(rows: list, out_path: str, **kwargs) -> str:
    html = generate_html(rows, **kwargs)
    import os
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)
    return out_path
